Fix encoded URL + Namespace no longer required
gravitee-io/gravitee-fetcher-gitlab pull request #20
Opened 2022-01-04 15:17 UTC by bastiendechamps

## Quick fixes
* Remove the wrong UTF-8 encoding of the generated path of the generated GitLab API URL `...projects/<namespace>/<project_id>...` when configuring a documentation for an API with the GitLab fetcher.
* Make the namespace no longer required (in several use cases there is no namespace). In that case the URL is `...projects//<project_id>...` but it works anyway.

2022-01-19 13:25 UTC, bastiendechamps commented
Bonjour, Est-il possible de savoir quand pourra être mergée cette PR de votre côté ? Merci.

2022-03-21 15:41 UTC, gcusnieux commented
Hi @bastiendechamps ! 
Thanks for your PR and sorry for the late reply.
I will have a look this week .

2022-03-23 14:44 UTC, gcusnieux requested changes

2022-03-23 14:44 UTC, gcusnieux commented on src/main/java/io/gravitee/fetcher/gitlab/GitlabFetcher.java
> +                    + '/'
Could you remove the slash if there is no namespace?

2022-03-23 14:44 UTC, gcusnieux commented on src/main/resources/schemas/schema-form.json
> -    "namespace",
Could you add default value as empty for namespace property ?

2022-03-23 14:47 UTC, gcusnieux commented on src/main/java/io/gravitee/fetcher/gitlab/GitlabFetcher.java
> +                    + '/'
And also fix `buildEditUrl()` method in this case please

2022-04-12 08:34 UTC, gcusnieux commented
Hello @bastiendechamps, I can't find any use case where namesapce is not required or empty.
Could you give me one?
Or send me a link to the Gitlab documentation or changelog please?

2022-05-30 13:18 UTC, closed without merging